### ISSUE TITLE
"SyntaxError: Non-ASCII character '\xe2'"

### ISSUE THREAD

**Issue by gray-area** [Ge0rg3/sans-index-creator#1]
I am trying to use this to index my course materials, but I am having an issue with the following error:

`SyntaxError: Non-ASCII character '\xe2' in file sans_indexer.py on line 35, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

Have you seen this before? Is it possible to get your help in getting this resolved?

Thanks

**Comment by gray-area** [comment]
Line 35 in the sans_indexer.py is the following:

`characters_to_strip = "()'\":,”“‘?;-•’—…[]!"`

If there is anything else I can do to help get this resolved, let me know.

**Comment by gray-area** [comment]
@Ge0rg3 

I may have figured out what the issue is, and I am testing it now. If it works, I will post back here the resolution.

**Comment by Ge0rg3** [comment]
Hi, usually you can add the following:
```
# -*- coding: utf-8 -*-
```
to the top of the python script, and the issue should be resolved. Does this fix work for you?

**Comment by gray-area** [comment]
@Ge0rg3 

Yes, that worked! I was able to add this to the script yesterday, and it functioned as needed. Thanks for the response, and thanks for the great project. It saves A LOT of time.

**Comment by MMMveasy** [comment]
After adding "# -*- coding: utf-8 -*-" to the top, i get this error: 

`File "sans_indexer.py", line 113
    results.append(f"{word}: {', '.join(pages_word_is_in)}")
                                                          ^
SyntaxError: invalid syntax
`

**Comment by NormalTechGuy** [comment]
I had a similar issue.

```python
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1086: character maps to <undefined>
```

What fixed it for me was adding `encoding='utf-8'` to line 69 as such:

```python
with open(options.input_file, "r", encoding='utf-8') as f:
```

**Comment by Ge0rg3** [comment]
Hey @NormalTechGuy, thanks - this looks like a better fix. If you have some free time please feel free to PR 😉
